---
- hosts: virtual
  name: Docker Container Creator
  remote_user: invoron
  become: true
  tasks:

    - name: install docker
      apt:
        name: docker.io
      when: ansible_os_family == 'Debian'
      tags:
        - docker

    - name: install python-docker
      apt:
        name: python-docker
        update_cache: yes
      when: ansible_os_family == 'Debian'
      tags:
        - python-docker 
