---
- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
  become: true
  tasks:
  - name: Create Odoo Mount Volumes ({{ ansible_user_id }}/odooxxx-addons)
    file:
      path: /home/{{ ansible_user_id }}/odoo1022-addons
      state: directory
    file:
      path: /home/{{ ansible_user_id }}/odoo112-addons
      state: directory
    file:
      path: /home/{{ ansible_user_id }}/odoo122-addons
      state: directory
