---
- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
  become: true
  tasks:
    - name: Ensure permission 0644 on /etc/group
      file:
        path="{{item}}"
        mode=0644
      with_items:
        - /etc/group

    - name: Ensure permission 0640 on /etc/gshadow
      file:
        path="{{item}}"
        mode=0640
      with_items:
        - /etc/gshadow

    - name: Ensure permission 0644 on /etc/passwd
      file:
        path="{{item}}"
        mode=0644
      with_items:
        - /etc/passwd

    - name: Ensure permission 0640 on /etc/shadow
      file:
        path="{{item}}"
        mode=0640
      with_items:
        - /etc/shadow

    - name: Ensure auditd is installed
      package:
        name="{{item}}"
        state=present
      with_items:
        - auditd

    - name: Ensure cron is installed
      package:
        name="{{item}}"
        state=present
      with_items:
        - cron

    - name: Ensure inetutils-telnetd is removed
      package:
        name="{{item}}"
        state=absent
      with_items:
        - inetutils-telnetd

    - name: Ensure nis is removed
      package:
        name="{{item}}"
        state=absent
      with_items:
        - nis

    - name: Ensure ntpdate is removed
      package:
        name="{{item}}"
        state=absent
      with_items:
        - ntpdate

    - name: Ensure ntp is installed
      package:
        name="{{item}}"
        state=present
      with_items:
        - ntp

    - name: Ensure rsyslog is installed
      package:
        name="{{item}}"
        state=present
      with_items:
        - rsyslog

    - name: Ensure telnetd is removed
      package:
        name="{{item}}"
        state=absent
      with_items:
        - telnetd

    - name: Ensure telnetd-ssl is removed
      package:
        name="{{item}}"
        state=absent
      with_items:
        - telnetd-ssl

    - name: enable service auditd
      service:
        name="{{item}}"
        enabled="yes"
        state="started"
      with_items:
        - auditd

    - name: enable service cron
      service:
        name="{{item}}"
        enabled="yes"
        state="started"
      with_items:
        - cron

    - name: enable service rsyslog
      service:
        name="{{item}}"
        enabled="yes"
        state="started"
      with_items:
        - rsyslog
