---
- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
  become: true
  tasks:

    - name: update and upgrade system
      apt:
        update_cache: yes
        upgrade: yes
      tags: ['apt']

    - name: install nginx
      apt:
        name: nginx
      tags: ['nginx']

    - name: install openssh-server
      apt:
        name: openssh-server
        state: present
      tags: ['openssh']

    - name: install lynis
      apt:
        name: lynis
        state: present
      tags: ['lynis','never']

    - name: install openvas
      apt:
        name: openvas
        state: present
      tags: ['openvas','never']

    - name: install openvpn
      apt:
        name: openvpn
        state: present
      tags:
      - openvpn

    - name: install python-pip
      apt:
        name: ['python-pip', 'python3-pip']
        state: present
      tags: ['pip']

    - name: install cockpit
      apt:
        name: cockpit
        state: present
      tags: ['cockpit']

    - name: Install lxd and lxc-utils
      apt:
        name: ['lxd','lxc-utils','lxd-tools']
        state: present
      when: ansible_os_family == 'Debian'
      tags: ['lxd','lxc','never']

    - name: Cloning LXDUI.
      git:
        repo: https://github.com/AdaptiveScale/lxdui.git
        version: master
        dest: /opt/
      accept_hostkey: yes
      tags: ['never','lxdui']
