---
- hosts: localhost
  vars:
    username: $USER
  become: true
  tasks:
    - name: Cloning LXDUI.
      git:
        repo: https://github.com/AdaptiveScale/lxdui.git
        version: master
        dest: /opt/
        accept_hostkey: yes

    - name: update and upgrade system
      apt:
        update_cache: yes
        upgrade: yes
      tags:
        - apt
    - name: install nginx
      apt:
        name: nginx
      tags:
        - nginx

    - name: install openssh-server
      apt:
        name: openssh-server
        state: present
      tags:
        - openssh

    - name: install openvpn
      apt:
        name: openvpn
        state: present
      tags:
        - openvpn

    - name: install python-pip
      apt:
        name: ['python-pip', 'python3-pip']
        state: present
      tags:
        - pip

    - name: install cockpit
      apt:
        name: cockpit
        state: present
      tags:
        - cockpit

    - name: install nginx
      apt:
        name: nginx
        state: present
      ta Cloning LXDUI.gate repository into /opt.
          git:
        repgit
        version: master
        dest: /opt/private-repo
    accept_hostkey: yes

    - name: install lxd
      apt:
        name: openssh-server
        state: present
      tags:
        - openssh
