---
- hosts: localhost
  vars:
    dockerstation: "https://github.com/DockStation/dockstation/releases/download/v1.4.1/dockstation_1.4.1_amd64.deb"
    username: "{{ ansible_user }}"
  become: true
  tasks:

    - name: update and upgrade system
      apt:
        update_cache: yes
        upgrade: yes
      tags: ['apt']

    - name: install nginx
      apt:
        name: nginx
      tags: ['nginx']

    - name: install openssh-server
      apt:
        name: openssh-server
        state: present
      tags: ['openssh']

    - name: install lynis
      apt:
        name: lynis
        state: present
      tags: ['lynis','never']

    - name: install openvas
      apt:
        name: openvas
        state: present
      tags: ['openvas','never']

    - name: install openvpn
      apt:
        name: openvpn
        state: present
      tags:
      - openvpn

    - name: install python-pip
      apt:
        name: ['python-pip', 'python3-pip']
        state: present
      tags: ['pip']

    - name: install cockpit
      apt:
        name: cockpit
        state: present
      tags: ['cockpit']

    - name: install zfs-utils
      apt:
        name: ['zfsutils-linux', 'zfs-dkms' ,'zfsutils-linux']
        state: present
      tags: ['lxd','never']

    - name: Install lxd and lxc-utils
      apt:
        name: ['lxc-utils','lxc']
        state: present
      when: ansible_os_family == 'Debian'
      tags: ['lxc','never']

    - name: Install lxd from snap
      command: snap install lxd --classic
      tags: ['lxd','never']

    - name: Cloning LXDUI.
      git:
        repo: https://github.com/AdaptiveScale/lxdui.git
        version: master
        dest: /opt/
      accept_hostkey: yes
      tags: ['never','lxdui']

    - name: Download dockerstation
      get_url: url="{{ dockerstation }}"
        dest="/home/{{ username }}/Downloads/{{ dockerstation }}.deb"
      tags: ['docker','dockerstation']

    - name: Install dockerstation
      apt: deb="/home/{{ username }}/Downloads/{{ dockerstation }}.deb"
        state=present
        tags: ['docker','dockerstation']
      sudo: true
- import_playbook: openscap.yml
